### ISSUE TITLE
Magnifik zoom-out (with Mobify.js)

### ISSUE THREAD

**Issue by nastiatikk** [mobify/magnifik#1]
Seems Magnifik dosn't work internal when you try to zoom-out.

The code:
{>_moduleScript:magnifik/}
(function($) {
	$('a.magnifik').magnifik(); 
})(Mobify.$)

The mistake console message when zoom-out:
Uncaught TypeError: Object #<Object> has no method 'detach'    magnifik.min.js:2
t.UI.Magnifik.e.close     magnifik.min.js:2
boundClose     magnifik.min.js:2
proxyfn

Here is what I got from talks with the team:

Zepto is built into Mobify.js and it doesn't have detach method. It can be fixed with jQuery but since there is a Zepto you can't simply add it. So I guess some addition to documentation should be added about how to connect jQuery for internal use (probably not here on GitHub but in JIRA for locals) or make the fix in JS to let it works.

**Comment by tedtate** [comment]
@nastiatikk this is resolved in later versions of Zepto (>= 1.0)
