### ISSUE TITLE
Reset scale on close

### ISSUE THREAD

**Issue by roboticarm** [mobify/magnifik#12]
Hi.  Thanks for making a fantastic and simple image enlargement.  It meets my needs perfectly, with one minor exception:  scaling the enlargement also scales the page that the enlargement is linked from.  So if I close the enlargement without zooming back to the initial display scale, I get a weird, zoomed-in page.

I understand that the pinch-zoom scaling is native and operating outside the CSS/HTML rendering of the browser.  But it seems to me that the initial scale could be reset on the close event.  Is this something that is possible and that you'd be willing to provide code for or add to the script itself?

**Comment by fractaltheory** [comment]
Hey, thanks for the information on the issue. We're currently in the process of rebuilding this plugin, so we'll ensure that this is taken into account once we've relaunched the new version. Closing this issue for now.
