### ISSUE TITLE
I can't seem to hook into the magnifik:close event

### ISSUE THREAD

**Issue by korynorthrop** [mobify/magnifik#19]
I am trying to run some code after the Magnifik image closes. The documentation mentions there's an Event for this (magnifik:close), but I can't seem to figure out how to utilize it. This is the code I'm trying now:

```
$('a.magnifik').magnifik({
    close: function() {
        alert('hi');
    }
});
```

Please let me know what I'm doing wrong.

Thanks!

**Comment by tedtate** [comment]
Assuming I'm reading the magnifik source correctly, I think you want something like:

```
$('.magnifik').on('magnifik:close', function() {
    console.log('do stuff');
});
```

This event is triggered from - https://github.com/mobify/magnifik/blob/master/src/magnifik.js#L157. Alternatively there is a `magnifik:closing` event that fires a little earlier.

**Comment by korynorthrop** [comment]
Perfect! Thank you.
