### ISSUE TITLE
Magnifik doesn't work well when pinch & zoom is enabled

### ISSUE THREAD

**Issue by jackygilbertson** [mobify/magnifik#3]
When pinch & zoom is left enabled on mobile, Magnifik behaves… strangely. It's odd to zoom and scroll around the page as well as the Magnifik frame.

Perhaps we should disable pinch & zoom when Maginfik is activated?

(Feel free to come by/ask me for any clarification… this is a bit of a nebulous issue)

**Comment by tedtate** [comment]
Agreed. This is something that will be part of the specification for our next updates to magnifik
