### ISSUE TITLE
Magnifik panning doesn’t work on Android 2.3 Browser

### ISSUE THREAD

**Issue by ry5n** [mobify/magnifik#5]
On older Android devices (specifically 2.3.3 Browser), panning won’t work on the opened magnifik canvas. Steps to reproduce:

- Using Android 2.3.3 Browser, navigate to http://mobify.github.io/magnifik/
- Tap the lovely Mr. Murray
- Try to pan

Expected: it pans; actual: no dice.

**Comment by tedtate** [comment]
I think Android 2.3 is beyond the scope of what we want to support with this plugin currently.
