### ISSUE TITLE
Incorrect position when re-zooming

### ISSUE THREAD

**Issue by thdoan** [mobify/magnifik#9]
When you initially click on the image to zoom, it correctly positions where you click at the center of the viewport. However, when you close magnifik and  click again to re-zoom, the positioning is now at the absolute top/left. It doesn't so bad with the default ratio of 2, but when you increase the ratio to something like 6, you will likely just see white space when you zoom in because the actual image is in the center (forcing you to pan to it).

**Comment by fractaltheory** [comment]
Hey thdoan, as per your other issue, we're currently rebuilding Magnifik --- we'll ensure this issue is looked after before relaunching. Thanks for the help! Closing for now.
